<option value="Abadan">Abadan</option>
<option value="Ahar">Ahar</option>
<option value="Ahvaz">Ahvaz</option>
<option value="Amol">Amol</option>
<option value="Andimeshk">Andimeshk</option>
<option value="Andisheh">Andisheh</option>
<option value="Arak">Arak</option>
<option value="Ardabil">Ardabil</option>
<option value="Babol">Babol</option>
<option value="Bam">Bam</option>
<option value="Bandar Abbas">Bandar Abbas</option>
<option value="Bandar-e Anzali">Bandar-e Anzali</option>
<option value="Bandar-e Mahshahr">Bandar-e Mahshahr</option>
<option value="Baneh">Baneh</option>
<option value="Behbahan">Behbahan</option>
<option value="Birjand">Birjand</option>
<option value="Bojnord">Bojnord</option>
<option value="Borazjan">Borazjan</option>
<option value="Borujerd">Borujerd</option>
<option value="Bukan">Bukan</option>
<option value="Bushehr">Bushehr</option>
<option value="Chabahar">Chabahar</option>
<option value="Dezful">Dezful</option>
<option value="Dorud">Dorud</option>
<option value="Eslamshahr">Eslamshahr</option>
<option value="Fardis">Fardis</option>
<option value="Fasa">Fasa</option>
<option value="Golestan">Golestan</option>
<option value="Gonbad-e Kavus">Gonbad-e Kavus</option>
<option value="Gorgan">Gorgan</option>
<option value="Hamadan">Hamadan</option>
<option value="Ilam">Ilam</option>
<option value="Iranshahr">Iranshahr</option>
<option value="Isfahan">Isfahan</option>
<option value="Izeh">Izeh</option>
<option value="Jahrom">Jahrom</option>
<option value="Jiroft">Jiroft</option>
<option value="Kamal Shahr">Kamal Shahr</option>
<option value="Karaj">Karaj</option>
<option value="Kashan">Kashan</option>
<option value="Kashmar">Kashmar</option>
<option value="Kerman">Kerman</option>
<option value="Kermanshah">Kermanshah</option>
<option value="Khomeyni Shahr">Khomeyni Shahr</option>
<option value="Khorramabad">Khorramabad</option>
<option value="Khorramshahr">Khorramshahr</option>
<option value="Khoy">Khoy</option>
<option value="Lahijan">Lahijan</option>
<option value="Mahabad">Mahabad</option>
<option value="Malard">Malard</option>
<option value="Malayer">Malayer</option>
<option value="Maragheh">Maragheh</option>
<option value="Marand">Marand</option>
<option value="Marivan">Marivan</option>
<option value="Marvdasht">Marvdasht</option>
<option value="Mashhad">Mashhad</option>
<option value="Masjed Soleyman">Masjed Soleyman</option>
<option value="Miandoab">Miandoab</option>
<option value="Mohammadshahr">Mohammadshahr</option>
<option value="Najafabad">Najafabad</option>
<option value="Nasimshahr">Nasimshahr</option>
<option value="Nazarabad">Nazarabad</option>
<option value="Nishapur">Nishapur</option>
<option value="Pakdasht">Pakdasht</option>
<option value="Qaem Shahr">Qaem Shahr</option>
<option value="Qarchak">Qarchak</option>
<option value="Qazvin">Qazvin</option>
<option value="Qods">Qods</option>
<option value="Qom">Qom</option>
<option value="Quchan">Quchan</option>
<option value="Rafsanjan">Rafsanjan</option>
<option value="Rasht">Rasht</option>
<option value="Robat Karim">Robat Karim</option>
<option value="Sabzevar">Sabzevar</option>
<option value="Sanandaj">Sanandaj</option>
<option value="Saqqez">Saqqez</option>
<option value="Sari">Sari</option>
<option value="Saveh">Saveh</option>
<option value="Semnan">Semnan</option>
<option value="Shahin Shahr">Shahin Shahr</option>
<option value="Shahr-e Kord">Shahr-e Kord</option>
<option value="Shahreza">Shahreza</option>
<option value="Shahriar">Shahriar</option>
<option value="Shahrud">Shahrud</option>
<option value="Shiraz">Shiraz</option>
<option value="Shushtar">Shushtar</option>
<option value="Sirjan">Sirjan</option>
<option value="Tabriz">Tabriz</option>
<option value="Tehran">Tehran</option>
<option value="Torbat-e Heydarieh">Torbat-e Heydarieh</option>
<option value="Torbat-e Jam">Torbat-e Jam</option>
<option value="Urmia">Urmia</option>
<option value="Varamin">Varamin</option>
<option value="Yasuj">Yasuj</option>
<option value="Yazd">Yazd</option>
<option value="Zabol">Zabol</option>
<option value="Zahedan">Zahedan</option>
<option value="Zanjan">Zanjan</option>